// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.2
// source: merged_profile.proto

package ppmerge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MergedByteProfile may represent merged profiles downloaded with debug option
type MergedByteProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profiles [][]byte `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
}

func (x *MergedByteProfile) Reset() {
	*x = MergedByteProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_profile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergedByteProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergedByteProfile) ProtoMessage() {}

func (x *MergedByteProfile) ProtoReflect() protoreflect.Message {
	mi := &file_merged_profile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergedByteProfile.ProtoReflect.Descriptor instead.
func (*MergedByteProfile) Descriptor() ([]byte, []int) {
	return file_merged_profile_proto_rawDescGZIP(), []int{0}
}

func (x *MergedByteProfile) GetProfiles() [][]byte {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// MergedProfile represents several profiles in a single profile
type MergedProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SampleType     []int64          `protobuf:"varint,1,rep,packed,name=sample_type,json=sampleType,proto3" json:"sample_type,omitempty"`
	Samples        []*MergeSample   `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	Functions      []*MergeFunction `protobuf:"bytes,3,rep,name=functions,proto3" json:"functions,omitempty"`
	Locations      []*MergeLocation `protobuf:"bytes,4,rep,name=locations,proto3" json:"locations,omitempty"`
	Mappings       []*MergeMapping  `protobuf:"bytes,5,rep,name=mappings,proto3" json:"mappings,omitempty"`
	PeriodTypes    []int64          `protobuf:"varint,6,rep,packed,name=period_types,json=periodTypes,proto3" json:"period_types,omitempty"`
	Periods        []int64          `protobuf:"varint,7,rep,packed,name=periods,proto3" json:"periods,omitempty"`
	TimesNanos     []int64          `protobuf:"varint,8,rep,packed,name=times_nanos,json=timesNanos,proto3" json:"times_nanos,omitempty"`
	DurationsNanos []int64          `protobuf:"varint,9,rep,packed,name=durations_nanos,json=durationsNanos,proto3" json:"durations_nanos,omitempty"`
	StringTable    []string         `protobuf:"bytes,10,rep,name=string_table,json=stringTable,proto3" json:"string_table,omitempty"`
	NumFunctions   []uint64         `protobuf:"varint,11,rep,packed,name=num_functions,json=numFunctions,proto3" json:"num_functions,omitempty"`
	NumLocations   []uint64         `protobuf:"varint,12,rep,packed,name=num_locations,json=numLocations,proto3" json:"num_locations,omitempty"`
	NumSampleTypes []uint64         `protobuf:"varint,13,rep,packed,name=num_sample_types,json=numSampleTypes,proto3" json:"num_sample_types,omitempty"`
	NumMappings    []uint64         `protobuf:"varint,14,rep,packed,name=num_mappings,json=numMappings,proto3" json:"num_mappings,omitempty"`
	NumSamples     []uint64         `protobuf:"varint,15,rep,packed,name=num_samples,json=numSamples,proto3" json:"num_samples,omitempty"`
}

func (x *MergedProfile) Reset() {
	*x = MergedProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_profile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergedProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergedProfile) ProtoMessage() {}

func (x *MergedProfile) ProtoReflect() protoreflect.Message {
	mi := &file_merged_profile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergedProfile.ProtoReflect.Descriptor instead.
func (*MergedProfile) Descriptor() ([]byte, []int) {
	return file_merged_profile_proto_rawDescGZIP(), []int{1}
}

func (x *MergedProfile) GetSampleType() []int64 {
	if x != nil {
		return x.SampleType
	}
	return nil
}

func (x *MergedProfile) GetSamples() []*MergeSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *MergedProfile) GetFunctions() []*MergeFunction {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *MergedProfile) GetLocations() []*MergeLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *MergedProfile) GetMappings() []*MergeMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

func (x *MergedProfile) GetPeriodTypes() []int64 {
	if x != nil {
		return x.PeriodTypes
	}
	return nil
}

func (x *MergedProfile) GetPeriods() []int64 {
	if x != nil {
		return x.Periods
	}
	return nil
}

func (x *MergedProfile) GetTimesNanos() []int64 {
	if x != nil {
		return x.TimesNanos
	}
	return nil
}

func (x *MergedProfile) GetDurationsNanos() []int64 {
	if x != nil {
		return x.DurationsNanos
	}
	return nil
}

func (x *MergedProfile) GetStringTable() []string {
	if x != nil {
		return x.StringTable
	}
	return nil
}

func (x *MergedProfile) GetNumFunctions() []uint64 {
	if x != nil {
		return x.NumFunctions
	}
	return nil
}

func (x *MergedProfile) GetNumLocations() []uint64 {
	if x != nil {
		return x.NumLocations
	}
	return nil
}

func (x *MergedProfile) GetNumSampleTypes() []uint64 {
	if x != nil {
		return x.NumSampleTypes
	}
	return nil
}

func (x *MergedProfile) GetNumMappings() []uint64 {
	if x != nil {
		return x.NumMappings
	}
	return nil
}

func (x *MergedProfile) GetNumSamples() []uint64 {
	if x != nil {
		return x.NumSamples
	}
	return nil
}

// ValueType describes the semantics and measurement units of a value.
type MergeValueType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int64 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` // Index into string table.
	Unit int64 `protobuf:"varint,2,opt,name=unit,proto3" json:"unit,omitempty"` // Index into string table.
}

func (x *MergeValueType) Reset() {
	*x = MergeValueType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_profile_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeValueType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeValueType) ProtoMessage() {}

func (x *MergeValueType) ProtoReflect() protoreflect.Message {
	mi := &file_merged_profile_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeValueType.ProtoReflect.Descriptor instead.
func (*MergeValueType) Descriptor() ([]byte, []int) {
	return file_merged_profile_proto_rawDescGZIP(), []int{2}
}

func (x *MergeValueType) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MergeValueType) GetUnit() int64 {
	if x != nil {
		return x.Unit
	}
	return 0
}

type MergeSample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationId []int64 `protobuf:"varint,1,rep,packed,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Value      []int64 `protobuf:"varint,2,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *MergeSample) Reset() {
	*x = MergeSample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_profile_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeSample) ProtoMessage() {}

func (x *MergeSample) ProtoReflect() protoreflect.Message {
	mi := &file_merged_profile_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeSample.ProtoReflect.Descriptor instead.
func (*MergeSample) Descriptor() ([]byte, []int) {
	return file_merged_profile_proto_rawDescGZIP(), []int{3}
}

func (x *MergeSample) GetLocationId() []int64 {
	if x != nil {
		return x.LocationId
	}
	return nil
}

func (x *MergeSample) GetValue() []int64 {
	if x != nil {
		return x.Value
	}
	return nil
}

type LocationID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []int64 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (x *LocationID) Reset() {
	*x = LocationID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_profile_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocationID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationID) ProtoMessage() {}

func (x *LocationID) ProtoReflect() protoreflect.Message {
	mi := &file_merged_profile_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationID.ProtoReflect.Descriptor instead.
func (*LocationID) Descriptor() ([]byte, []int) {
	return file_merged_profile_proto_rawDescGZIP(), []int{4}
}

func (x *LocationID) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

type FunctionCompact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []int64 `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *FunctionCompact) Reset() {
	*x = FunctionCompact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_profile_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionCompact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCompact) ProtoMessage() {}

func (x *FunctionCompact) ProtoReflect() protoreflect.Message {
	mi := &file_merged_profile_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCompact.ProtoReflect.Descriptor instead.
func (*FunctionCompact) Descriptor() ([]byte, []int) {
	return file_merged_profile_proto_rawDescGZIP(), []int{5}
}

func (x *FunctionCompact) GetData() []int64 {
	if x != nil {
		return x.Data
	}
	return nil
}

type FunctionOrFunctionRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to FunctionOrRef:
	//
	//	*FunctionOrFunctionRef_Function
	//	*FunctionOrFunctionRef_Ref
	FunctionOrRef isFunctionOrFunctionRef_FunctionOrRef `protobuf_oneof:"functionOrRef"`
}

func (x *FunctionOrFunctionRef) Reset() {
	*x = FunctionOrFunctionRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_profile_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionOrFunctionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionOrFunctionRef) ProtoMessage() {}

func (x *FunctionOrFunctionRef) ProtoReflect() protoreflect.Message {
	mi := &file_merged_profile_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionOrFunctionRef.ProtoReflect.Descriptor instead.
func (*FunctionOrFunctionRef) Descriptor() ([]byte, []int) {
	return file_merged_profile_proto_rawDescGZIP(), []int{6}
}

func (m *FunctionOrFunctionRef) GetFunctionOrRef() isFunctionOrFunctionRef_FunctionOrRef {
	if m != nil {
		return m.FunctionOrRef
	}
	return nil
}

func (x *FunctionOrFunctionRef) GetFunction() *MergeFunction {
	if x, ok := x.GetFunctionOrRef().(*FunctionOrFunctionRef_Function); ok {
		return x.Function
	}
	return nil
}

func (x *FunctionOrFunctionRef) GetRef() *FunctionRef {
	if x, ok := x.GetFunctionOrRef().(*FunctionOrFunctionRef_Ref); ok {
		return x.Ref
	}
	return nil
}

type isFunctionOrFunctionRef_FunctionOrRef interface {
	isFunctionOrFunctionRef_FunctionOrRef()
}

type FunctionOrFunctionRef_Function struct {
	Function *MergeFunction `protobuf:"bytes,1,opt,name=function,proto3,oneof"`
}

type FunctionOrFunctionRef_Ref struct {
	Ref *FunctionRef `protobuf:"bytes,2,opt,name=ref,proto3,oneof"`
}

func (*FunctionOrFunctionRef_Function) isFunctionOrFunctionRef_FunctionOrRef() {}

func (*FunctionOrFunctionRef_Ref) isFunctionOrFunctionRef_FunctionOrRef() {}

type FunctionRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FunctionRefId uint64 `protobuf:"varint,2,opt,name=function_ref_id,json=functionRefId,proto3" json:"function_ref_id,omitempty"`
}

func (x *FunctionRef) Reset() {
	*x = FunctionRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_profile_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionRef) ProtoMessage() {}

func (x *FunctionRef) ProtoReflect() protoreflect.Message {
	mi := &file_merged_profile_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionRef.ProtoReflect.Descriptor instead.
func (*FunctionRef) Descriptor() ([]byte, []int) {
	return file_merged_profile_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionRef) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FunctionRef) GetFunctionRefId() uint64 {
	if x != nil {
		return x.FunctionRefId
	}
	return 0
}

type MergeFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique nonzero function id
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the function, in human-readable form if available.
	Name int64 `protobuf:"varint,3,opt,name=name,proto3" json:"name,omitempty"` // Index into string table
	// Name of the function, as identified by the system.
	// For instance, it can be a C++ mangled name.
	SystemName int64 `protobuf:"varint,4,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"` // Index into string table
	// Source file containing the function.
	Filename int64 `protobuf:"varint,5,opt,name=filename,proto3" json:"filename,omitempty"` // Index into string table
	// Line number in source file.
	StartLine int64 `protobuf:"varint,6,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
}

func (x *MergeFunction) Reset() {
	*x = MergeFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_profile_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeFunction) ProtoMessage() {}

func (x *MergeFunction) ProtoReflect() protoreflect.Message {
	mi := &file_merged_profile_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeFunction.ProtoReflect.Descriptor instead.
func (*MergeFunction) Descriptor() ([]byte, []int) {
	return file_merged_profile_proto_rawDescGZIP(), []int{8}
}

func (x *MergeFunction) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MergeFunction) GetName() int64 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *MergeFunction) GetSystemName() int64 {
	if x != nil {
		return x.SystemName
	}
	return 0
}

func (x *MergeFunction) GetFilename() int64 {
	if x != nil {
		return x.Filename
	}
	return 0
}

func (x *MergeFunction) GetStartLine() int64 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

type MergeLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique nonzero id for the location.  A profile could use
	// instruction addresses or any integer sequence as ids.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The id of the corresponding profile.Mapping for this location.
	// It can be unset if the mapping is unknown or not applicable for
	// this profile type.
	MappingId uint64 `protobuf:"varint,2,opt,name=mapping_id,json=mappingId,proto3" json:"mapping_id,omitempty"`
	// The instruction address for this location, if available.  It
	// should be within [Mapping.memory_start...Mapping.memory_limit]
	// for the corresponding mapping. A non-leaf address may be in the
	// middle of a call instruction. It is up to display tools to find
	// the beginning of the instruction if necessary.
	Address uint64 `protobuf:"varint,3,opt,name=address,proto3" json:"address,omitempty"`
	// Multiple line indicates this location has inlined functions,
	// where the last entry represents the caller into which the
	// preceding entries were inlined.
	//
	// E.g., if memcpy() is inlined into printf:
	//
	//	line[0].function_name == "memcpy"
	//	line[1].function_name == "printf"
	Line []*MergeLine `protobuf:"bytes,4,rep,name=line,proto3" json:"line,omitempty"`
	// Provides an indication that multiple symbols map to this location's
	// address, for example due to identical code folding by the linker. In that
	// case the line information above represents one of the multiple
	// symbols. This field must be recomputed when the symbolization state of the
	// profile changes.
	IsFolded bool `protobuf:"varint,5,opt,name=is_folded,json=isFolded,proto3" json:"is_folded,omitempty"`
}

func (x *MergeLocation) Reset() {
	*x = MergeLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_profile_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeLocation) ProtoMessage() {}

func (x *MergeLocation) ProtoReflect() protoreflect.Message {
	mi := &file_merged_profile_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeLocation.ProtoReflect.Descriptor instead.
func (*MergeLocation) Descriptor() ([]byte, []int) {
	return file_merged_profile_proto_rawDescGZIP(), []int{9}
}

func (x *MergeLocation) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MergeLocation) GetMappingId() uint64 {
	if x != nil {
		return x.MappingId
	}
	return 0
}

func (x *MergeLocation) GetAddress() uint64 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *MergeLocation) GetLine() []*MergeLine {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *MergeLocation) GetIsFolded() bool {
	if x != nil {
		return x.IsFolded
	}
	return false
}

type MergeLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the corresponding profile.Function for this line.
	FunctionId uint64 `protobuf:"varint,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	// Line number in source code.
	Line int64 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
}

func (x *MergeLine) Reset() {
	*x = MergeLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_profile_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeLine) ProtoMessage() {}

func (x *MergeLine) ProtoReflect() protoreflect.Message {
	mi := &file_merged_profile_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeLine.ProtoReflect.Descriptor instead.
func (*MergeLine) Descriptor() ([]byte, []int) {
	return file_merged_profile_proto_rawDescGZIP(), []int{10}
}

func (x *MergeLine) GetFunctionId() uint64 {
	if x != nil {
		return x.FunctionId
	}
	return 0
}

func (x *MergeLine) GetLine() int64 {
	if x != nil {
		return x.Line
	}
	return 0
}

type MergeMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique nonzero id for the mapping.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Address at which the binary (or DLL) is loaded into memory.
	MemoryStart uint64 `protobuf:"varint,2,opt,name=memory_start,json=memoryStart,proto3" json:"memory_start,omitempty"`
	// The limit of the address range occupied by this mapping.
	MemoryLimit uint64 `protobuf:"varint,3,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	// Offset in the binary that corresponds to the first mapped address.
	FileOffset uint64 `protobuf:"varint,4,opt,name=file_offset,json=fileOffset,proto3" json:"file_offset,omitempty"`
	// The object this entry is loaded from.  This can be a filename on
	// disk for the main binary and shared libraries, or virtual
	// abstractions like "[vdso]".
	Filename int64 `protobuf:"varint,5,opt,name=filename,proto3" json:"filename,omitempty"` // Index into string table
	// A string that uniquely identifies a particular program version
	// with high probability. E.g., for binaries generated by GNU tools,
	// it could be the contents of the .note.gnu.build-id field.
	BuildId int64 `protobuf:"varint,6,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"` // Index into string table
	// The following fields indicate the resolution of symbolic info.
	HasFunctions    bool `protobuf:"varint,7,opt,name=has_functions,json=hasFunctions,proto3" json:"has_functions,omitempty"`
	HasFilenames    bool `protobuf:"varint,8,opt,name=has_filenames,json=hasFilenames,proto3" json:"has_filenames,omitempty"`
	HasLineNumbers  bool `protobuf:"varint,9,opt,name=has_line_numbers,json=hasLineNumbers,proto3" json:"has_line_numbers,omitempty"`
	HasInlineFrames bool `protobuf:"varint,10,opt,name=has_inline_frames,json=hasInlineFrames,proto3" json:"has_inline_frames,omitempty"`
}

func (x *MergeMapping) Reset() {
	*x = MergeMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_profile_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeMapping) ProtoMessage() {}

func (x *MergeMapping) ProtoReflect() protoreflect.Message {
	mi := &file_merged_profile_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeMapping.ProtoReflect.Descriptor instead.
func (*MergeMapping) Descriptor() ([]byte, []int) {
	return file_merged_profile_proto_rawDescGZIP(), []int{11}
}

func (x *MergeMapping) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MergeMapping) GetMemoryStart() uint64 {
	if x != nil {
		return x.MemoryStart
	}
	return 0
}

func (x *MergeMapping) GetMemoryLimit() uint64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *MergeMapping) GetFileOffset() uint64 {
	if x != nil {
		return x.FileOffset
	}
	return 0
}

func (x *MergeMapping) GetFilename() int64 {
	if x != nil {
		return x.Filename
	}
	return 0
}

func (x *MergeMapping) GetBuildId() int64 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

func (x *MergeMapping) GetHasFunctions() bool {
	if x != nil {
		return x.HasFunctions
	}
	return false
}

func (x *MergeMapping) GetHasFilenames() bool {
	if x != nil {
		return x.HasFilenames
	}
	return false
}

func (x *MergeMapping) GetHasLineNumbers() bool {
	if x != nil {
		return x.HasLineNumbers
	}
	return false
}

func (x *MergeMapping) GetHasInlineFrames() bool {
	if x != nil {
		return x.HasInlineFrames
	}
	return false
}

var File_merged_profile_proto protoreflect.FileDescriptor

var file_merged_profile_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x6d, 0x65, 0x72,
	0x67, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x2f, 0x0a, 0x11, 0x4d, 0x65,
	0x72, 0x67, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x8d, 0x05, 0x0a, 0x0d,
	0x4d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x39,
	0x0a, 0x07, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x52, 0x07, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x09, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64,
	0x75, 0x6d, 0x6d, 0x79, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3f, 0x0a, 0x09, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x64, 0x75, 0x6d, 0x6d, 0x79, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3c, 0x0a, 0x08, 0x6d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x64, 0x75, 0x6d, 0x6d, 0x79, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52,
	0x08, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x0b, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x70,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x5f,
	0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x0e, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4e, 0x61, 0x6e, 0x6f, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x75, 0x6d, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0c, 0x6e, 0x75, 0x6d, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x75, 0x6d, 0x5f,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x0c, 0x6e, 0x75, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x28, 0x0a,
	0x10, 0x6e, 0x75, 0x6d, 0x5f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0e, 0x6e, 0x75, 0x6d, 0x53, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x5f, 0x6d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0b, 0x6e,
	0x75, 0x6d, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75,
	0x6d, 0x5f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x0a, 0x6e, 0x75, 0x6d, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x4d,
	0x65, 0x72, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0x44, 0x0a, 0x0b, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x53, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1c, 0x0a, 0x0a, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x0f, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x9e, 0x01, 0x0a, 0x15, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x72, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x66, 0x12, 0x3f, 0x0a, 0x08, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64,
	0x75, 0x6d, 0x6d, 0x79, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x03, 0x72,
	0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79,
	0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x66, 0x48, 0x00, 0x52, 0x03, 0x72, 0x65, 0x66,
	0x42, 0x0f, 0x0a, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x72, 0x52, 0x65,
	0x66, 0x22, 0x45, 0x0a, 0x0b, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x66,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x26, 0x0a, 0x0f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x66,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x66, 0x49, 0x64, 0x22, 0x8f, 0x01, 0x0a, 0x0d, 0x4d, 0x65, 0x72,
	0x67, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0xa8, 0x01, 0x0a, 0x0d, 0x4d,
	0x65, 0x72, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x31, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x6d, 0x65, 0x72, 0x67, 0x65,
	0x64, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x4c, 0x69,
	0x6e, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x66,
	0x6f, 0x6c, 0x64, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x46,
	0x6f, 0x6c, 0x64, 0x65, 0x64, 0x22, 0x40, 0x0a, 0x09, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x4c, 0x69,
	0x6e, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0xdc, 0x02, 0x0a, 0x0c, 0x4d, 0x65, 0x72, 0x67,
	0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x5f, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x68,
	0x61, 0x73, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x68,
	0x61, 0x73, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x68, 0x61, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x12, 0x28, 0x0a, 0x10, 0x68, 0x61, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x68, 0x61, 0x73, 0x4c,
	0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x68, 0x61,
	0x73, 0x5f, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x68, 0x61, 0x73, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x65, 0x64, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2f, 0x70, 0x70, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_merged_profile_proto_rawDescOnce sync.Once
	file_merged_profile_proto_rawDescData = file_merged_profile_proto_rawDesc
)

func file_merged_profile_proto_rawDescGZIP() []byte {
	file_merged_profile_proto_rawDescOnce.Do(func() {
		file_merged_profile_proto_rawDescData = protoimpl.X.CompressGZIP(file_merged_profile_proto_rawDescData)
	})
	return file_merged_profile_proto_rawDescData
}

var file_merged_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_merged_profile_proto_goTypes = []interface{}{
	(*MergedByteProfile)(nil),     // 0: dummymergedprofile.MergedByteProfile
	(*MergedProfile)(nil),         // 1: dummymergedprofile.MergedProfile
	(*MergeValueType)(nil),        // 2: dummymergedprofile.MergeValueType
	(*MergeSample)(nil),           // 3: dummymergedprofile.MergeSample
	(*LocationID)(nil),            // 4: dummymergedprofile.LocationID
	(*FunctionCompact)(nil),       // 5: dummymergedprofile.FunctionCompact
	(*FunctionOrFunctionRef)(nil), // 6: dummymergedprofile.FunctionOrFunctionRef
	(*FunctionRef)(nil),           // 7: dummymergedprofile.FunctionRef
	(*MergeFunction)(nil),         // 8: dummymergedprofile.MergeFunction
	(*MergeLocation)(nil),         // 9: dummymergedprofile.MergeLocation
	(*MergeLine)(nil),             // 10: dummymergedprofile.MergeLine
	(*MergeMapping)(nil),          // 11: dummymergedprofile.MergeMapping
}
var file_merged_profile_proto_depIdxs = []int32{
	3,  // 0: dummymergedprofile.MergedProfile.samples:type_name -> dummymergedprofile.MergeSample
	8,  // 1: dummymergedprofile.MergedProfile.functions:type_name -> dummymergedprofile.MergeFunction
	9,  // 2: dummymergedprofile.MergedProfile.locations:type_name -> dummymergedprofile.MergeLocation
	11, // 3: dummymergedprofile.MergedProfile.mappings:type_name -> dummymergedprofile.MergeMapping
	8,  // 4: dummymergedprofile.FunctionOrFunctionRef.function:type_name -> dummymergedprofile.MergeFunction
	7,  // 5: dummymergedprofile.FunctionOrFunctionRef.ref:type_name -> dummymergedprofile.FunctionRef
	10, // 6: dummymergedprofile.MergeLocation.line:type_name -> dummymergedprofile.MergeLine
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_merged_profile_proto_init() }
func file_merged_profile_proto_init() {
	if File_merged_profile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_merged_profile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergedByteProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_profile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergedProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_profile_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeValueType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_profile_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeSample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_profile_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocationID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_profile_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionCompact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_profile_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionOrFunctionRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_profile_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_profile_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_profile_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_profile_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_profile_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_merged_profile_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*FunctionOrFunctionRef_Function)(nil),
		(*FunctionOrFunctionRef_Ref)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_merged_profile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_merged_profile_proto_goTypes,
		DependencyIndexes: file_merged_profile_proto_depIdxs,
		MessageInfos:      file_merged_profile_proto_msgTypes,
	}.Build()
	File_merged_profile_proto = out.File
	file_merged_profile_proto_rawDesc = nil
	file_merged_profile_proto_goTypes = nil
	file_merged_profile_proto_depIdxs = nil
}
